# Logfile created on 2018-11-15 20:40:18 +0100 by logger.rb/61378
I, [2018-11-15T20:40:18.224315 #20386]  INFO -- : [*] consumer waiting
E, [2018-11-15T20:40:20.120308 #20386] ERROR -- : [e] Exception occured -> #<ActiveRecord::StatementInvalid: PG::InsufficientPrivilege: ERROR:  permission denied for relation readouts
: INSERT INTO "readouts" ("data_type", "content", "created_at", "updated_at", "message_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id">
E, [2018-11-15T20:40:23.151869 #20386] ERROR -- : [e] Exception occured -> #<ActiveRecord::StatementInvalid: PG::InsufficientPrivilege: ERROR:  permission denied for relation readouts
: INSERT INTO "readouts" ("data_type", "content", "created_at", "updated_at", "message_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id">
E, [2018-11-15T20:40:25.947662 #20386] ERROR -- : [e] Exception occured -> #<ActiveRecord::StatementInvalid: PG::InsufficientPrivilege: ERROR:  permission denied for relation readouts
: INSERT INTO "readouts" ("data_type", "content", "created_at", "updated_at", "message_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id">
E, [2018-11-15T20:40:28.667989 #20386] ERROR -- : [e] Exception occured -> #<ActiveRecord::StatementInvalid: PG::InsufficientPrivilege: ERROR:  permission denied for relation readouts
: INSERT INTO "readouts" ("data_type", "content", "created_at", "updated_at", "message_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id">
E, [2018-11-15T20:40:31.430506 #20386] ERROR -- : [e] Exception occured -> #<ActiveRecord::StatementInvalid: PG::InsufficientPrivilege: ERROR:  permission denied for relation readouts
: INSERT INTO "readouts" ("data_type", "content", "created_at", "updated_at", "message_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id">
E, [2018-11-15T20:40:33.371606 #20386] ERROR -- : [e] Exception occured -> Interrupt
I, [2018-11-15T20:41:21.039095 #20826]  INFO -- : [*] consumer waiting
E, [2018-11-15T20:41:23.076456 #20826] ERROR -- : [e] Exception occured -> #<ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, adc0, {"adc":"18"}, 2018-11-15 19:41:23.07111, 2018-11-15 19:41:23.07111, 1).
: INSERT INTO "readouts" ("data_type", "content", "created_at", "updated_at", "message_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id">
E, [2018-11-15T20:41:25.859350 #20826] ERROR -- : [e] Exception occured -> #<ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, adc0, {"adc":"18"}, 2018-11-15 19:41:25.85558, 2018-11-15 19:41:25.85558, 1).
: INSERT INTO "readouts" ("data_type", "content", "created_at", "updated_at", "message_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id">
E, [2018-11-15T20:41:28.579908 #20826] ERROR -- : [e] Exception occured -> #<ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, adc0, {"adc":"18"}, 2018-11-15 19:41:28.573894, 2018-11-15 19:41:28.573894, 1).
: INSERT INTO "readouts" ("data_type", "content", "created_at", "updated_at", "message_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id">
E, [2018-11-15T20:41:31.167600 #20826] ERROR -- : [e] Exception occured -> #<ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, adc0, {"adc":"18"}, 2018-11-15 19:41:31.163288, 2018-11-15 19:41:31.163288, 1).
: INSERT INTO "readouts" ("data_type", "content", "created_at", "updated_at", "message_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id">
E, [2018-11-15T20:41:33.827137 #20826] ERROR -- : [e] Exception occured -> #<ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, adc0, {"adc":"18"}, 2018-11-15 19:41:33.820949, 2018-11-15 19:41:33.820949, 1).
: INSERT INTO "readouts" ("data_type", "content", "created_at", "updated_at", "message_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id">
E, [2018-11-15T20:41:36.336076 #20826] ERROR -- : [e] Exception occured -> #<ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, adc0, {"adc":"18"}, 2018-11-15 19:41:36.326501, 2018-11-15 19:41:36.326501, 1).
: INSERT INTO "readouts" ("data_type", "content", "created_at", "updated_at", "message_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id">
E, [2018-11-15T20:41:39.197328 #20826] ERROR -- : [e] Exception occured -> #<ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, adc0, {"adc":"18"}, 2018-11-15 19:41:39.175297, 2018-11-15 19:41:39.175297, 1).
: INSERT INTO "readouts" ("data_type", "content", "created_at", "updated_at", "message_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id">
E, [2018-11-15T20:41:42.054538 #20826] ERROR -- : [e] Exception occured -> #<ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, adc0, {"adc":"18"}, 2018-11-15 19:41:42.048465, 2018-11-15 19:41:42.048465, 1).
: INSERT INTO "readouts" ("data_type", "content", "created_at", "updated_at", "message_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id">
E, [2018-11-15T20:41:46.521564 #20826] ERROR -- : [e] Exception occured -> #<ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, adc0, {"adc":"18"}, 2018-11-15 19:41:46.508654, 2018-11-15 19:41:46.508654, 1).
: INSERT INTO "readouts" ("data_type", "content", "created_at", "updated_at", "message_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id">
E, [2018-11-15T20:41:49.909150 #20826] ERROR -- : [e] Exception occured -> #<ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, adc0, {"adc":"18"}, 2018-11-15 19:41:49.901055, 2018-11-15 19:41:49.901055, 1).
: INSERT INTO "readouts" ("data_type", "content", "created_at", "updated_at", "message_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id">
E, [2018-11-15T20:41:53.062118 #20826] ERROR -- : [e] Exception occured -> #<ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, adc0, {"adc":"18"}, 2018-11-15 19:41:53.055398, 2018-11-15 19:41:53.055398, 1).
: INSERT INTO "readouts" ("data_type", "content", "created_at", "updated_at", "message_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id">
E, [2018-11-15T20:41:56.864267 #20826] ERROR -- : [e] Exception occured -> #<ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, adc0, {"adc":"18"}, 2018-11-15 19:41:56.807587, 2018-11-15 19:41:56.807587, 1).
: INSERT INTO "readouts" ("data_type", "content", "created_at", "updated_at", "message_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id">
E, [2018-11-15T20:42:00.606930 #20826] ERROR -- : [e] Exception occured -> #<ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, adc0, {"adc":"18"}, 2018-11-15 19:42:00.599292, 2018-11-15 19:42:00.599292, 1).
: INSERT INTO "readouts" ("data_type", "content", "created_at", "updated_at", "message_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id">
E, [2018-11-15T20:42:04.076392 #20826] ERROR -- : [e] Exception occured -> #<ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, adc0, {"adc":"18"}, 2018-11-15 19:42:04.052111, 2018-11-15 19:42:04.052111, 1).
: INSERT INTO "readouts" ("data_type", "content", "created_at", "updated_at", "message_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id">
E, [2018-11-15T20:42:07.211439 #20826] ERROR -- : [e] Exception occured -> #<ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, adc0, {"adc":"18"}, 2018-11-15 19:42:07.194343, 2018-11-15 19:42:07.194343, 1).
: INSERT INTO "readouts" ("data_type", "content", "created_at", "updated_at", "message_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id">
E, [2018-11-15T20:42:10.759342 #20826] ERROR -- : [e] Exception occured -> #<ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, adc0, {"adc":"18"}, 2018-11-15 19:42:10.733235, 2018-11-15 19:42:10.733235, 1).
: INSERT INTO "readouts" ("data_type", "content", "created_at", "updated_at", "message_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id">
E, [2018-11-15T20:42:14.079055 #20826] ERROR -- : [e] Exception occured -> #<ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, adc0, {"adc":"18"}, 2018-11-15 19:42:14.065944, 2018-11-15 19:42:14.065944, 1).
: INSERT INTO "readouts" ("data_type", "content", "created_at", "updated_at", "message_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id">
E, [2018-11-15T20:42:17.453895 #20826] ERROR -- : [e] Exception occured -> #<ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, adc0, {"adc":"18"}, 2018-11-15 19:42:17.44293, 2018-11-15 19:42:17.44293, 1).
: INSERT INTO "readouts" ("data_type", "content", "created_at", "updated_at", "message_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id">
E, [2018-11-15T20:42:20.961354 #20826] ERROR -- : [e] Exception occured -> #<ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, adc0, {"adc":"18"}, 2018-11-15 19:42:20.932669, 2018-11-15 19:42:20.932669, 1).
: INSERT INTO "readouts" ("data_type", "content", "created_at", "updated_at", "message_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id">
E, [2018-11-15T20:42:24.871593 #20826] ERROR -- : [e] Exception occured -> #<ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, adc0, {"adc":"18"}, 2018-11-15 19:42:24.867232, 2018-11-15 19:42:24.867232, 1).
: INSERT INTO "readouts" ("data_type", "content", "created_at", "updated_at", "message_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id">
E, [2018-11-15T20:42:28.703845 #20826] ERROR -- : [e] Exception occured -> #<ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, adc0, {"adc":"18"}, 2018-11-15 19:42:28.684264, 2018-11-15 19:42:28.684264, 1).
: INSERT INTO "readouts" ("data_type", "content", "created_at", "updated_at", "message_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id">
E, [2018-11-15T20:42:33.003835 #20826] ERROR -- : [e] Exception occured -> #<ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, adc0, {"adc":"18"}, 2018-11-15 19:42:32.998589, 2018-11-15 19:42:32.998589, 1).
: INSERT INTO "readouts" ("data_type", "content", "created_at", "updated_at", "message_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id">
E, [2018-11-15T20:42:36.021989 #20826] ERROR -- : [e] Exception occured -> #<ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, adc0, {"adc":"18"}, 2018-11-15 19:42:36.016232, 2018-11-15 19:42:36.016232, 1).
: INSERT INTO "readouts" ("data_type", "content", "created_at", "updated_at", "message_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id">
E, [2018-11-15T20:42:39.759962 #20826] ERROR -- : [e] Exception occured -> #<ActiveRecord::StatementInvalid: PG::InsufficientPrivilege: ERROR:  permission denied for sequence readouts_id_seq
: INSERT INTO "readouts" ("data_type", "content", "created_at", "updated_at", "message_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id">
E, [2018-11-15T20:42:42.618333 #20826] ERROR -- : [e] Exception occured -> #<ActiveRecord::StatementInvalid: PG::InsufficientPrivilege: ERROR:  permission denied for sequence readouts_id_seq
: INSERT INTO "readouts" ("data_type", "content", "created_at", "updated_at", "message_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id">
E, [2018-11-15T20:42:45.412926 #20826] ERROR -- : [e] Exception occured -> #<ActiveRecord::StatementInvalid: PG::InsufficientPrivilege: ERROR:  permission denied for sequence readouts_id_seq
: INSERT INTO "readouts" ("data_type", "content", "created_at", "updated_at", "message_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id">
E, [2018-11-15T20:42:48.890962 #20826] ERROR -- : [e] Exception occured -> #<ActiveRecord::StatementInvalid: PG::InsufficientPrivilege: ERROR:  permission denied for sequence readouts_id_seq
: INSERT INTO "readouts" ("data_type", "content", "created_at", "updated_at", "message_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id">
E, [2018-11-15T20:42:53.828792 #20826] ERROR -- : [e] Exception occured -> #<ActiveRecord::StatementInvalid: PG::InsufficientPrivilege: ERROR:  permission denied for sequence readouts_id_seq
: INSERT INTO "readouts" ("data_type", "content", "created_at", "updated_at", "message_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id">
E, [2018-11-15T20:42:57.057743 #20826] ERROR -- : [e] Exception occured -> #<RuntimeError: !>
E, [2018-11-15T20:42:59.952605 #20826] ERROR -- : [e] Exception occured -> #<RuntimeError: !>
E, [2018-11-15T20:43:02.736969 #20826] ERROR -- : [e] Exception occured -> #<RuntimeError: !>
E, [2018-11-15T20:43:05.588908 #20826] ERROR -- : [e] Exception occured -> #<RuntimeError: !>
E, [2018-11-15T20:43:08.495438 #20826] ERROR -- : [e] Exception occured -> #<RuntimeError: !>
E, [2018-11-15T20:43:11.500508 #20826] ERROR -- : [e] Exception occured -> #<RuntimeError: !>
E, [2018-11-15T20:43:14.148561 #20826] ERROR -- : [e] Exception occured -> #<RuntimeError: !>
E, [2018-11-15T20:43:16.057445 #20826] ERROR -- : [e] Exception occured -> Interrupt
E, [2018-11-15T20:43:17.281238 #20826] ERROR -- : [e] Exception occured -> Interrupt
I, [2018-11-15T20:43:56.934423 #21376]  INFO -- : [*] consumer waiting
E, [2018-11-15T20:43:58.982464 #21376] ERROR -- : [e] Exception occured -> #<RuntimeError: !>
E, [2018-11-15T20:44:01.789190 #21376] ERROR -- : [e] Exception occured -> #<RuntimeError: !>
E, [2018-11-15T20:44:04.273629 #21376] ERROR -- : [e] Exception occured -> #<RuntimeError: !>
E, [2018-11-15T20:44:07.127857 #21376] ERROR -- : [e] Exception occured -> #<RuntimeError: !>
E, [2018-11-15T20:44:09.717014 #21376] ERROR -- : [e] Exception occured -> #<RuntimeError: !>
E, [2018-11-15T20:44:12.282578 #21376] ERROR -- : [e] Exception occured -> #<RuntimeError: !>
E, [2018-11-15T20:44:13.692690 #21376] ERROR -- : [e] Exception occured -> Interrupt
I, [2018-11-15T20:44:27.074990 #21446]  INFO -- : [*] consumer waiting
